name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test --verbose
      - name: rust-grcov
        uses: actions-rs/grcov@v0.1.5
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          verbose: true
          fail_ci_if_error: true
